# This file was generated by `rails generate rspec:install`.
# The settings below are requested by the default configuration of rspec-rails.
#
# For more information, see the rspec-rails README:
# https://github.com/rspec/rspec-rails

# This is a basic, Rails-agnostic spec helper. Rails-specific setup lives in
# spec/rails_helper.rb.

# --- Code coverage (SimpleCov) -------------------------------------------
# This file is loaded first (via the `--require spec_helper` option in .rspec),
# before spec/rails_helper.rb boots Rails, so SimpleCov can start tracking
# before any application code is loaded.
#
# Run the suite (e.g. through the profile-gated test service, see TESTING.md)
# and the results are written to coverage/ (a self-contained HTML report under
# coverage/index.html). That directory is git-ignored.
require "simplecov"

SimpleCov.start do
  # Only report on the application code: keep app/, lib/ and the root-level
  # files, and exclude the spec suite itself (SimpleCov's default filters
  # already cover /spec/, /test/ and /vendor/) and everything installed under
  # the container's gem path.
  SimpleCov.skip %r{/spec/}
  SimpleCov.skip %r{/test/}
  SimpleCov.skip %r{/vendor/}
  SimpleCov.skip %r{^/usr/local/bundle}
end
# ---------------------------------------------------------------------------
